* Arch Linux
#+BEGIN_QUOTE
ImprovingU for learning Arch Linux. From installation to maintenance.
#+END_QUOTE
* Installation Steps
Refer to the installation notes below while following the arch linux
installation guide.
1. Install Virtualbox
2. Download Arch Linux ISO
3. Configure a virtual machine through Virtualbox for Arch Linux
   1. I would use at least 2GB RAM and at least 32 GB of storage. You may want more.
   2. Ensure EFI boot is enabled
   3. Set VRAM to 128MB
   4. Enable 3D Hardware Acceleration
   5. Enable more CPU cores (Ideally you would enable as many as you have
      physical cores)
4. Boot up the virtual machine and when it asks select the Arch Linux ISO as the
   boot disk
5. Follow the [[https://wiki.archlinux.org/index.php/installation_guide][instructions]] on the Arch website for installing Arch Linux using
   the ISO
   1. When it comes to installing a bootloader follow the [[https://wiki.archlinux.org/index.php/GRUB#UEFI_systems][UEFI instructions]] for
      installing GRUB
6. Turn off the virtual machine
7. Remove the Arch Linux ISO from the virtual optical drive
8. Start the virtual machine
9. Log in with username ~root~, password is whatever you set during the
   installation steps

** Installation notes
*** Use gdisk for partitioning
- Need a EFI partition
  - 400MB is a good size
  - use partition code ~ef00~
  - format with ~mkfs.fat -F32 /dev/sda2~
- a swap partition
  - use partition code ~8200~
- and a Linux filesystem partition
  - use partition code ~8300~
*** Get mirrors
 - ~curl "https://www.archlinux.org/mirrorlist/?country=US&protocol=http&protocol=https&ip_version=4" | sed 's/^.//' > /etc/pacman.d/mirrorlist~
*** Timezone
 - ~ln -sf /usr/share/zoneinfo/America/Chicago /etc/localtime~
*** Set hostname 
 - ~echo arch-improvinu > /etc/hostname~
 - ~arch-improvingu~ can be replaced with whatever you want, it's a good idea to
   make it alpha-numeric
*** Grub install
 #+BEGIN_SRC sh
 $ pacman -S grub efibootmgr
 $ grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=arch --removable
 $ grub-mkconfig -o /boot/grub/grub.cfg
 #+END_SRC

* System Setup
** Enable networking
Networking was enabled in the installation media by default. This must be set up
after booting into our brand new Arch installation. After running these
commands, the service will startup automatically on boot.
#+BEGIN_SRC sh
$ systemctl enable dhcpcd.service
$ systemctl start dhcpcd.service
#+END_SRC

** Install virtual box guest utilities
When installing, ensure that you choose the arch option rather than the dkms option.
#+BEGIN_SRC sh
$ pacman -S linux-headers virtual-box-guest-utils
#+END_SRC

** Set up a non-root user
#+BEGIN_SRC sh
$ pacman -S sudo
$ useradd -m -g users -G wheel -s /bin/bash USERNAME
$ passwd USERNAME
#+END_SRC

** Install a desktop environment
Most people, when installing a desktop environment, also choose to install a
login manager.
#+BEGIN_SRC sh
$ sudo pacman -S gnome
#+END_SRC

Disable wayland by uncommenting the line to disable it in `/etc/gdm/custom.conf`

#+BEGIN_SRC sh
$ sudo pacman -S xf86-video-fbdev
$ sudo systemctl enable gdm.service
$ sudo systemctl start gdm.service



** Install a browser
#+BEGIN_SRC sh
$ sudo pacman -S chromium
#+END_SRC

